name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cpp_standard: [17, 20, 23]
        exclude:
          # C++23 is not yet fully supported on Windows MSVC in CI
          - os: windows-latest
            cpp_standard: 23
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        
        # Try to install Apache Arrow (optional, with timeout)
        timeout 300 sudo apt-get install -y libarrow-dev || true
    
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        echo Using pre-installed MSVC and CMake on Windows
    
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # CMake and Clang are pre-installed on macos-latest
        # Try to install Apache Arrow via homebrew (optional, with timeout)
        timeout 300 brew install apache-arrow || true
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standard }}
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Test
      working-directory: build
      run: ctest --output-on-failure