name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cpp_standard: [17, 20, 23]
        exclude:
          # C++23 is not yet fully supported on Windows MSVC in CI
          - os: windows-latest
            cpp_standard: 23
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        
        # Try to install Apache Arrow (optional, with simpler approach)
        sudo apt-get install -y libarrow-dev || echo "Arrow not available via apt, continuing without it"
    
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # CMake and MSVC are pre-installed on windows-latest
        # Apache Arrow installation on Windows is complex and optional for this template
        echo "Using pre-installed MSVC and CMake on Windows"
    
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # CMake and Clang are pre-installed on macos-latest
        # Try to install Apache Arrow via homebrew (optional)
        brew install apache-arrow || echo "Arrow not available via brew, continuing without it"
    
    - name: Configure CMake
      run: |
        echo "Configuring with C++${{ matrix.cpp_standard }}"
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standard }}
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Test
      run: |
        cd build
        ctest --output-on-failure